# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: local
    hooks:
    -   id: generate-rdocs
        name: Generate Rdoc's data
        description: This hook generates rdocs data
        entry: rdoc
        language: system
        types: [text]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

#Blank this out for now and then implement once we clean up code
#-   repo: https://github.com/jumanjihouse/pre-commit-hooks.git
#    rev: 2.1.3
#    hooks:
#    - id: reek
#    - id: rubocop
#    - id: fasterer