version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

#Initial rspec set up
jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.1
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: gem install rspec
          command: rspec
      - ruby/bundle-install
